In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import os
from sklearn.model_selection import train_test_split


In [7]:

# data_folder = r'C:/Users/bhave/Desktop/Akul/'

# # Initialize an empty dataframe
# data = pd.DataFrame()

# # Initialize a list to store one row from each CSV file
# rows = []

# # Initialize a label encoder
# le = LabelEncoder()

# # Loop over all CSV files in the data folder
# for filename in os.listdir(data_folder):
#     if filename.endswith('.csv'):
#         # Load the CSV file
#         df = pd.read_csv(os.path.join(data_folder, filename))
        
#         # Drop the first and second columns
#         df = df.drop(df.columns[0:2], axis=1)
        
#         # Add a new column for the labels (the filename without the .csv extension)
#         df['label'] = filename[:-4]
        
#         # Append the first row of the dataframe to the list
#         rows.append(df.iloc[0])
        
#         # Append the dataframe to the main dataframe
#         data = pd.concat([data, df])

# # Convert the labels to integers
# data['label'] = le.fit_transform(data['label'])

# # Create a dictionary that maps the original labels to the encoded values
# label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

# print(label_mapping)

# # Assume that all columns except 'label' are features
# X = data.drop('label', axis=1).values

# # Assume that the 'label' column is the target
# y = data['label'].values

# # Create a new dataframe from the list of rows
# rows_df = pd.DataFrame(rows)

# # Print the new dataframe
# print(rows_df)

In [8]:
#load check.csv

check = pd.read_csv('/Users/Aash/Desktop/Python/Words/check.csv')


In [9]:
check

flex_1  flex_2  flex_3  flex_4  flex_5        Qw        Qx        Qy  \
0        11.0     9.0    -7.0    -7.0    -3.0  0.268066  0.754700  0.018860   
1        12.0    10.0    -6.0    -6.0     0.0  0.266846  0.754822  0.019409   
2       -10.0     8.0    -5.0    -6.0    -4.0  0.265930  0.754761  0.019836   
3        12.0    10.0    -3.0    -7.0    -1.0  0.265198  0.754578  0.020081   
4        12.0     7.0    -7.0    -5.0    -4.0  0.264648  0.754150  0.020203   
...       ...     ...     ...     ...     ...       ...       ...       ...   
20995    22.0     0.0   -18.0    72.0    58.0  0.875183  0.096863 -0.473938   
20996    22.0     5.0   -17.0    74.0    57.0  0.874939  0.096619 -0.474487   
20997    23.0     6.0   -18.0    73.0    58.0  0.874695  0.096375 -0.474915   
20998    22.0     7.0   -15.0    72.0    55.0  0.874634  0.096008 -0.475098   
20999    22.0     5.0   -15.0    73.0    58.0  0.874756  0.095764 -0.474915   

             Qz      GYRx  ...      ACCx      ACCy      ACCz  ACCx_body  \
0      0.598450  0.091603  ...  9.347803  4.825830 -1.942773   0.594556   
1      0.598816  0.068702  ...  9.313110  4.821045 -1.928418   0.555078   
2      0.599243  0.045802  ...  9.279614  4.785156 -1.911670   0.517993   
3      0.599854  0.022901  ...  9.253296  4.718164 -1.898511   0.485693   
4      0.600586  0.015267  ...  9.234156  4.603320 -1.884155   0.460571   
...         ...       ...  ...       ...       ...       ...        ...   
20995 -0.000366 -0.007634  ...  7.797412  1.735815  5.085425  -0.331372   
20996 -0.000305 -0.015267  ...  7.887134  1.714282  5.129687  -0.248828   
20997 -0.000244 -0.015267  ...  8.019922  1.668823  5.160791  -0.120825   
20998 -0.000122 -0.015267  ...  8.138354  1.613794  5.178735  -0.004785   
20999  0.000061 -0.007634  ...  8.179029  1.576709  5.176343   0.035889   

       ACCy_body  ACCz_body  ACCx_world  ACCy_world  ACCz_world  label  
0       0.638818  -0.570630   -0.539526   -0.119629    0.882861      0  
1       0.644800  -0.552686   -0.535937   -0.148340    0.848169      0  
2       0.617285  -0.537134   -0.523975   -0.145947    0.800317      0  
3       0.559863  -0.529956   -0.509619   -0.111255    0.745288      0  
4       0.453394  -0.527563   -0.485693   -0.031104    0.677100      0  
...          ...        ...         ...         ...         ...    ...  
20995   0.070581  -0.126807   -0.082544    0.120825   -0.330176      8  
20996   0.053833  -0.074170   -0.078955    0.087329   -0.235669      8  
20997   0.013159  -0.034692   -0.038281    0.028711   -0.116040      8  
20998  -0.032300  -0.015552    0.013159   -0.027515   -0.016748      8  
20999  -0.064600  -0.021533    0.043066   -0.062207    0.007178      8  

[21000 rows x 22 columns]

In [10]:

# Assume that all columns except 'label' are features
X = check.drop('label', axis=1).values

# Assume that the 'label' column is the target
y = check['label'].values

In [11]:
# #save data to csv
# data.to_csv('check.csv', index=False)

In [12]:
X.shape

(21000, 21)

In [13]:
set(y)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13}

In [14]:
# {'bad': 0,
#  'deaf': 1,
#  'fine': 2,
#  'good': 3,
#  'goodbye': 4,
#  'hello': 5,
#  'hungry': 6,
#  'me': 7,
#  'no': 8,
#  'please': 9,
#  'sorry': 10,
#  'thankyou': 11,
#  'yes': 12,
#  'you': 13}

In [15]:
# label_mapping

In [16]:
from sklearn.model_selection import train_test_split

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

In [17]:
# from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler
# sc = RobustScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

In [18]:
from sklearn.preprocessing import MinMaxScaler

# Create a MinMaxScaler object with desired feature range
scaler = MinMaxScaler(feature_range=(-1, 1))

# Fit and transform your data
X_trainScaled = scaler.fit_transform(X_train)
X_testScaled = scaler.transform(X_test)



In [19]:
X_trainScaled

array([[-0.39285714,  0.15044248,  0.17241379, ...,  0.01407864,
        -0.01401551,  0.0878608 ],
       [ 0.42857143, -0.43362832, -0.54022989, ...,  0.0135252 ,
        -0.15470632,  0.20471726],
       [ 0.57142857,  1.        ,  0.4137931 , ...,  0.00985854,
         0.00291029,  0.19927428],
       ...,
       [ 0.14285714, -0.57522124,  0.44827586, ..., -0.00252516,
        -0.0247377 ,  0.19907268],
       [-0.375     , -0.4159292 , -0.47126437, ...,  0.00612266,
         0.05644478,  0.19745994],
       [-0.39285714, -0.66371681, -0.57471264, ...,  0.00958176,
         0.00528449,  0.20075261]])

In [20]:
from sklearn.ensemble import RandomForestClassifier

# Create a Decision Tree classifier
classifier = RandomForestClassifier(n_estimators=30, max_depth=2, random_state=42)

# Train the model
classifier.fit(X_trainScaled, y_train)

RandomForestClassifier(max_depth=2, n_estimators=30, random_state=42)

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, classifier.predict(X_testScaled))
print(cm)

[[121   0 136   0   3   0   0   0   0   7   0   0   0   0]
 [  0 299   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 328   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  22   0   0   0   0   0   0 300   0   0]
 [  0   1   0   0 271   0  27   0   0   0   2   2   0   0]
 [  0   0   0   0   0 327   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 299   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0 299   0   0   2   0   0   0]
 [  0   0   1   0   0   0   2   0 301   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0 268   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 279   0   0   0]
 [  0   0   0   0  26   1   0   0   0   0   0 267   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 301   0]
 [  0  15   0   0   0   0   5 107   0   0   1   0   0 175]]


In [22]:
accuracy = classifier.score(X_testScaled, y_test)

In [23]:
accuracy

0.8416666666666667

In [24]:
# Define the sample data point
# samples = np.array([[53.0, 52.0 ,87.0, 84.0, 61.0 ,0.762634, 0.620483, -0.182434, -0.000854, -0.007634, 0.0 ,0.0 ,2.941675, 10.066772, 1.567139, 0.224902, 0.788355, -0.0323 ,0.040674, 0.160303, 0.80271]])

samples = np.array([[ -3.0, 8.0 ,-13.0 ,-26.0 ,-5.0, 0.955078, 0.07196, 0.160217, -0.238586, 0.0 ,0.0 ,-0.007634 ,-3.352002 ,0.685474 ,9.37771 ,-0.015552 ,0.087329, 0.181836 ,0.077759, 0.044263, 0.18064
]])



In [25]:
samples = scaler.transform(samples)

In [26]:
samples

array([[-0.60714286, -0.4159292 , -0.57471264, -0.68867925, -0.43529412,
         0.88560562, -0.57546688,  0.73565756, -0.73324504,  0.41630899,
        -0.28623991,  0.45724895, -0.2590997 ,  0.00706256,  0.59050365,
         0.25603512, -0.01514232,  0.17391592,  0.0079906 ,  0.00436548,
         0.22783324]])

In [27]:
# Use the trained model to predict the label for the sample
prediction1 = classifier.predict(samples)

print(f'The predicted label for the sample is: {prediction1}')

The predicted label for the sample is: [2]


In [28]:
# Predict a random value from X_test

import random

# Select a random index from the test set
index = random.randint(0, len(X_test) - 1)

# Select a random sample from the test set
sample = X_test[index].reshape(1, -1)
sample = scaler.transform(sample)

# Use the trained model to predict the label for the sample
predictions = classifier.predict(sample)

# Get the actual label for the sample
actual_label = y_test[index]

print(f'The predicted label for the sample is: {predictions}')
print(f'The actual label for the sample is: {actual_label}')




The predicted label for the sample is: [2]
The actual label for the sample is: 0


In [29]:
sample

array([[-0.28571429, -0.38053097, -0.54022989, -0.44339623, -0.36470588,
         0.97275554, -0.54627655,  0.29125693, -0.38685698,  0.23390555,
        -0.54378224,  0.28996292, -0.06699277,  0.11417258,  0.52431092,
         0.11177763,  0.04195436,  0.09871612, -0.10961987,  0.08868804,
         0.13355509]])